class Data:
    number: int
    text: str

    def __init__(self, number: int, text: str):
        self.number = number
        self.text = text


def marshal(data: Data) -> str:
    """
    Create a serialization function that converts a Data object into a string.
    This string should encapsulate the content of the Data object.
    Later you should be able to use this string to generate a new Data object instance by unmarshalling it.

    To enhance your learning, avoid using pre-existing serialization libraries.
    Instead, develop your own method to convert a Data object into a textual format.
    Apply the skills you've acquired in string manipulation and type conversions for this task.
    """
    pass


def unmarshal(data_string: str) -> Data:
    """
    Convert a string representation of a Data object back into a Data object.

    The input string is assumed to be in a specific format generated by the `marshal` function.
    This function parses the string, extracts the relevant data (number and text),
    and creates a new instance of the Data class with these attributes.

    Parameters:
    data_string (str): A string representation of a Data object that the marshal function created.

    Returns:
    Data: A new instance of the Data class, populated with the data extracted from the input string.

    Note:
    This function should be designed to work in tandem with the `marshal` function.
    It should be able to correctly parse and convert any string that was created using the `marshal` function.
    The specific parsing logic will depend on the format chosen for the `marshal` function.

    Example:
    >>> data_string = marshal(Data(42, "The answer is fourty-two."))
    >>> data_object = unmarshal(data_string)
    >>> print(data_object.number)
    42
    >>> print(data_object.text)
    The answer is fourty-two.
    """

    # Parsing logic goes here. The implementation depends on the format used in marshal function.
    # For example, if marshal uses a certain format, you would need to extract the data based on that format here.
    # Then, convert the Data.number value from string to int after extraction and populate the field in a new Data object.
    pass
