#!/usr/bin/env bash
set -eE 

if [ -f "test_main.py" ]; then
  declare pycmd
  if type python3 &>/dev/null ; then
    pycmd="python3"
  else
    pycmd="python"
  fi
	"${pycmd}" -m unittest discover
fi

